name : Testing
on : 
   push:
    branches: 
      -main
      
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Python unit tests
      run: pytest --html=report.html --self-contained-html -s .\tests.py
